In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("borkowski_comps_1017.csv", header = None).T
df = df.iloc[:1018,:]
df.columns = df.iloc[0,:]
df = df.iloc[1:,:]
df

,Mg-glutamate (mM),K-glutamate (mM),Amino Acid (mM),tRNA (mg/ml),coA (mM),NAD (mM),cAMP (mM),Folinic Acid (mM),Spermidine (mM),3-PGA (mM),NTP (mM),Yield
1,4.0,80.0,1.5,0.2,0.26,0.33,0.75,0.068,1.0,30.0,0.45,0.00001
2,0.4,80.0,1.5,0.2,0.26,0.33,0.75,0.068,1.0,30.0,1.5,0.00001
3,4.0,80.0,1.5,0.2,0.26,0.33,0.75,0.068,1.0,30.0,0.15,0.00001
4,1.2,40.0,0.45,0.02,0.078,0.165,0.375,0.0204,0.3,9.0,0.75,0.00001
5,4.0,80.0,1.5,0.2,0.26,0.33,0.75,0.068,1.0,30.0,0.75,0.108
...,...,...,...,...,...,...,...,...,...,...,...,...
1013,4.0,80.0,1.5,0.06,0.078,0.165,0.075,0.0204,0.1,9.0,1.5,29.744
1014,4.0,80.0,1.5,0.1,0.026,0.099,0.075,0.0068,0.1,9.0,1.5,29.779
1015,4.0,80.0,1.5,0.06,0.078,0.033,0.075,0.0204,0.1,9.0,1.5,30.081
1016,4.0,80.0,1.5,0.1,0.026,0.099,0.075,0.034,0.1,9.0,1.5,32.983
1017,4.0,80.0,1.5,0.06,0.026,0.165,0.075,0.068,0.1,9.0,1.5,33.927

In [11]:
df.to_csv("borkowski_comps_1017_prepped.csv", index= False)